# Generated by Django 2.1.dev20171004182438 on 2017-10-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testbot', '0002_auto_20171006_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.CharField(max_length=2048),
        ),
        migrations.AddField(
            model_name='entities',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testbot.Example'),
        ),
    ]
