# Generated by Django 2.1.dev20171004182438 on 2017-10-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testbot', '0003_auto_20171024_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('payload', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntentEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(blank=True, max_length=2048, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testbot.EntityTypes')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testbot.Intent')),
            ],
        ),
        migrations.RemoveField(
            model_name='entities',
            name='example',
        ),
        migrations.DeleteModel(
            name='Entities',
        ),
    ]
